// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAMmJh3fXAsLfe1XVUA6kGm9kEHHuj5iRY",
    authDomain: "ocg-humanbionics.firebaseapp.com",
    projectId: "ocg-humanbionics",
    storageBucket: "ocg-humanbionics.firebasestorage.app",
    messagingSenderId: "196011124818",
    appId: "1:196011124818:web:c526108c8a981a71d7d78b",
    measurementId: "G-9WZ1GY1YZR",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLCvlzf2gml6yBxwDQyoCzFOoEEBKAMg',
    appId: '1:196011124818:android:808f8902b4d5c87bd7d78b',
    messagingSenderId: '196011124818',
    projectId: 'ocg-humanbionics',
    storageBucket: 'ocg-humanbionics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXxpdsE3KkG7jMVLPxxpzCf8MgR_qt4eI',
    appId: '1:196011124818:ios:9cf1592aaef0d693d7d78b',
    messagingSenderId: '196011124818',
    projectId: 'ocg-humanbionics',
    storageBucket: 'ocg-humanbionics.firebasestorage.app',
    iosBundleId: 'com.example.ocgProyect',
  );
}
